import { z } from "zod";
import { teamMemberRoleZod } from "./enums.zod.js";
import { zPhoneNumber, zString, zTimeEpoch, zTimestamps } from "./zod_utils.js";

/**
 * TeamApp Schemas
 */

export const teamAppAutoGeneratedZod = z.object({
  id: z.ulid(),
});

export const teamAppMandatoryZod = z.object({
  name: zString.min(1, "Team name is required"),
});

export const teamAppOptionalZod = z.object({
  logoUrl: z.url().max(2048).nullable(),
  createdByUserId: z.uuid(),
  personalTeamForUserId: z.uuid().nullable(),
  deletedAt: zTimeEpoch.nullable(),
});

export const teamAppCreateInputZod = teamAppMandatoryZod.extend(teamAppOptionalZod.partial().shape);
export type TeamAppCreateInput = z.infer<typeof teamAppCreateInputZod>;

// API-facing create schema. Excludes server-controlled identity/tenancy fields
// (`createdByUserId`, `personalTeamForUserId`, `deletedAt`) so authenticated
// clients can't spoof team ownership or burn another user's personal-team slot
// (soft-delete-partial unique on `personal_team_for_user_id`). The server
// derives `createdByUserId` from the session and never accepts
// `personalTeamForUserId` from clients — it's set only by server-only paths
// (`getDefaultTeam` / `UserTable.afterCreate`).
export const teamAppCreateApiInputZod = teamAppMandatoryZod.extend(
  teamAppOptionalZod.pick({ logoUrl: true }).partial().shape,
);
export type TeamAppCreateApiInput = z.infer<typeof teamAppCreateApiInputZod>;

export const teamAppSelectAllZod = teamAppMandatoryZod
  .extend(teamAppOptionalZod.shape)
  .extend(teamAppAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamAppSelectAll = z.infer<typeof teamAppSelectAllZod>;

/**
 * TeamMember Schemas
 */

export const teamAppMemberAutoGeneratedZod = z.object({
  id: z.ulid(),
});

export const teamAppMemberMandatoryZod = z.object({
  teamId: z.ulid(),
  role: teamMemberRoleZod,
  addedAt: zTimeEpoch,
});

export const teamAppMemberOptionalZod = z.object({
  userId: z.uuid().nullable(),
  email: z.email().max(320).nullable(),
  phoneNumber: zPhoneNumber.nullable(),
  joinedAt: zTimeEpoch.nullable(),
  deletedAt: zTimeEpoch.nullable(),
});

export const teamAppMemberSelectAllZod = teamAppMemberMandatoryZod
  .extend(teamAppMemberOptionalZod.shape)
  .extend(teamAppMemberAutoGeneratedZod.shape)
  .extend(zTimestamps);
export type TeamAppMemberSelectAll = z.infer<typeof teamAppMemberSelectAllZod>;

export const teamAppMemberRoleZod = teamMemberRoleZod;
export type TeamAppMemberRole = z.infer<typeof teamAppMemberRoleZod>;

// `teamId` is derived from the `x-team-id` header on the RPC procedure, not
// from the request body — callers implicitly add members to their active team.
export const teamAppMemberAddInputZod = z.object({
  email: z.email().max(320).optional().nullable(),
  phoneNumber: zPhoneNumber.optional().nullable(),
  role: teamMemberRoleZod,
}).refine(data => data.email || data.phoneNumber, {
  message: "Either email or phone number must be provided",
  path: ["email"],
});
export type TeamAppMemberAddInput = z.infer<typeof teamAppMemberAddInputZod>;

export const teamWithRoleZod = teamAppSelectAllZod.extend({
  joinedAt: zTimeEpoch.nullable(),
  userRole: teamMemberRoleZod,
});
export type TeamWithRole = z.infer<typeof teamWithRoleZod>;